import type { Metadata } from "next";
import "./globals.css";
import Headline from "@/components/layout/headline";
import Navbar from "@/components/layout/navbar";
import { inter } from "@/app/fonts";
import { CartProvider } from "@/components/layout/cart-provider";
import { Bounce, ToastContainer } from "react-toastify";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Refine - E commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      suppressHydrationWarning
      data-qb-installed="true">
      <body
        className={`${inter.variable} antialiased overflow-x-hidden`}
        cz-shortcut-listen="true"
      >
        <CartProvider>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            transition={Bounce}
          />

          <UserProvider>
            <Headline />
            <Navbar />
            {children}
          </UserProvider>
        </CartProvider>
      </body>
    </html>
  );
}
