import type { Metadata } from "next";
import "./globals.css";
import Headline from "@/components/layout/headline";
import Navbar from "@/components/layout/navbar";
import { instrumentSans } from "@/app/fonts";
import { CartProvider } from "@/components/layout/cart-provider";


export const metadata: Metadata = {
  title: "Refine - Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      suppressHydrationWarning
      data-qb-installed="true">
      <body
        className={`${instrumentSans.variable} antialiased overflow-x-hidden`}
        cz-shortcut-listen="true"
      >
        <CartProvider>
          <Headline />
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
